### ISSUE TITLE
Mirror - 快速搭建含留言功能的Blog

### ISSUE THREAD

**Issue by JeffKko** [JeffKko/blog#1]
# Mirror

a blog tool base on GitHub issues 

### 安裝

``` bash
# 注意M開頭為大寫
$ npm install Mirror -g
```

### 新建一個 blog

```bash
$ cd blog
$ mirror init
```

### 設置 token (已有token可以跳過此步驟)

`token` 是 GitHub API 驗證用的

在[這裏](https://github.com/settings/tokens)新增token

只需要讀取權限, 勾選以下兩項

- read: user Read all user profile data
- user: email Access user email addresses (read-only)

按下 `Generate Token` 就可以了

### 配置 blog

修改目錄中的 `config.yml`

範例 ：

``` yml
# 是否为组织项目
organization: false

# 文章排序，依据更新时间还是创建时间
# 值为 'UPDATED_AT' 或者 'CREATED_AT'
order: 'UPDATED_AT'

# 网站标题
title: my blog

# GitHub 用户名或者组织名
user: jeffkko

# 项目名称，项目里面的 issues 是你的博客内容
# 如果你的项目是组织项目，请设置 'organization' 为 true
repository: blog

# 多用户设置，上面设置的 user 用户名默认已经包括
# 多用户名字必须用 ',' 分割
# 例子: author0,author1
authors:

# token 设置
# token 必须以 '#' 分割
# 如果你的 token 是 5c31bffc137f44faf7efc4a84da827g7ca2cfeaa 
# 那么这里填入的值为 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa

# 文章列表分页
perpage: 10
```

注意剛剛拿到的token必須隨機插入一個 `#` 做分割, 沒有的話等等上傳到 github 會被刪除

### 生成 blog

``` bash
$ mirror build
```

### 發佈到 github

所有内容都 push 到一個 repository 的 gh-pages 分支

### 設置 GitHub Pages

到該 repository 的 setting -> `GitHub Pages`

這裏可以發布一個 gitbuh pages, branch 選擇 `gh-pages`

成功的話會看到一段訊息：`Your site is published at https://<user>.github.io/<repository>/`

到這邊算是建置完成了

### 設定客製化域名

通過修改 `CNAME`, 可以藉由 DNS 轉發, 設置自己的 domain

參考這篇文章 [gh-pages 域名绑定](https://segmentfault.com/a/1190000011203711)

### 完成

現在可以在 `github issue` 上面寫 blog 了, `https://<user>.github.io/<repository>` 或是自己 `自訂的網域` 都會同步更新所有內容！

# 參考

[Demo](https://github.com/JeffKko/blog/issues)

[source](https://github.com/LoeiFy/Mirror)

[LoeiFy's blog](https://mirror.am0200.com/)
